name: Run RDRSS Script 2

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: # 수동 실행 버튼

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소 코드 가져오기
      uses: actions/checkout@v6

    - name: 파이썬(Python) 설치
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
        
    - name: 의존성 라이브러리 설치
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: RDRSS 초기설정 및 실행
      env:
        RD_SECRET_TOKEN: ${{ secrets.REAL_DEBRID_TOKEN }}
        # RDRSS가 무조건 현재 폴더 아래를 데이터 저장소로 인식하도록 강제 지정합니다.
        XDG_DATA_HOME: ${{ github.workspace }}/.config
        XDG_CONFIG_HOME: ${{ github.workspace }}/.config
      run: |
        # 1. 강제 지정한 경로 하위에 올바른 폴더 생성
        mkdir -p ${{ github.workspace }}/.config/RDRSS
        
        # 2. rdrss.json 파일 동적 생성
        echo '{
          "authToken": "'"$RD_SECRET_TOKEN"'",
          "rssUrls": [
            "https://bt4gprx.com/search?q=h264-f1rst 때리는&page=rss",
            "https://bt4gprx.com/search?q=골 때리는 그녀들 720p-NEXT&page=rss"
          ],
          "updated": 0
        }' > ${{ github.workspace }}/.config/RDRSS/rdrss.json

        # 3. 인자 없이 순수 실행
        python RDRSS.py
